import argparse

parser = argparse.ArgumentParser(description='DeSC')
parser.add_argument('--seed', default=234, type=int)
parser.add_argument('--embed-dim', default=512, type=int)
parser.add_argument('--visual-length', default=256, type=int)
parser.add_argument('--visual-width', default=512, type=int)
parser.add_argument('--visual-head', default=1, type=int)
parser.add_argument('--visual-layers', default=2, type=int)
parser.add_argument('--attn-window', default=8, type=int)
parser.add_argument('--prompt-prefix', default=10, type=int)
parser.add_argument('--prompt-postfix', default=10, type=int)
parser.add_argument('--classes-num', default=14, type=int)
parser.add_argument('--max-epoch', default=10, type=int)
parser.add_argument('--model-path', default='../model/model_ucf.pth')
parser.add_argument('--use-checkpoint', default=False, type=bool)
parser.add_argument('--checkpoint-path', default='../model/checkpoint_ucf.pth')
parser.add_argument('--batch-size', default=64, type=int)
parser.add_argument('--train-list', default='../list/ucf_CLIP_rgb.csv')
parser.add_argument('--test-list', default='../list/ucf_CLIP_rgbtest.csv')
parser.add_argument('--gt-path', default='../list/gt_ucf.npy')
parser.add_argument('--gt-segment-path', default='../list/gt_segment_ucf.npy')
parser.add_argument('--gt-label-path', default='../list/gt_label_ucf.npy')
parser.add_argument('--lr', default=5e-5, type=float)
parser.add_argument('--weight_decay', type=float, default=1e-5, help='Weight decay for AdamW optimizer')
parser.add_argument('--scheduler-rate', default=0.1)
parser.add_argument('--scheduler-milestones', default=[4, 8])
parser.add_argument('--graph_head', type=int, default=2, help='Number of attention heads in Graph Transformer')
parser.add_argument('--graph_layers', type=int, default=1, help='Number of layers in Graph Transformer')
parser.add_argument('--tcn_levels', type=int, default=7, help='Number of levels (blocks) in the TCN module.')
parser.add_argument('--tcn_kernel_size', type=int, default=5, help='Kernel size for the TCN convolutions.')
parser.add_argument('--lambda_gmm', type=float, default=0.7, help='Weight for GMP consistency loss')
parser.add_argument('--gmp_beta', type=float, default=0.7, help='Beta for Gaussian mask variance')
parser.add_argument('--ensemble_weight_sota2', type=float, default=0.5, help='The weight for the ensemble.')

