import argparse

parser = argparse.ArgumentParser(description='DeSC')
parser.add_argument('--seed', default=234, type=int)
parser.add_argument('--embed-dim', default=512, type=int)
parser.add_argument('--visual-length', default=256, type=int)
parser.add_argument('--visual-width', default=512, type=int)
parser.add_argument('--visual-head', default=1, type=int)
parser.add_argument('--visual-layers', default=1, type=int)
parser.add_argument('--attn-window', default=64, type=int)
parser.add_argument('--prompt-prefix', default=10, type=int)
parser.add_argument('--prompt-postfix', default=10, type=int)
parser.add_argument('--classes-num', default=7, type=int)
parser.add_argument('--max-epoch', default=10, type=int)
parser.add_argument('--model-path', default='../model/model_xd.pth')
parser.add_argument('--use-checkpoint', default=False, type=bool)
parser.add_argument('--checkpoint-path', default='../model/checkpoint_xd.pth')
parser.add_argument('--batch-size', default=96, type=int)
parser.add_argument('--train-list', default='../list/xd_CLIP_rgb.csv')
parser.add_argument('--test-list', default='../list/xd_CLIP_rgbtest.csv')
parser.add_argument('--gt-path', default='../list/gt.npy')
parser.add_argument('--gt-segment-path', default='../list/gt_segment.npy')
parser.add_argument('--gt-label-path', default='../list/gt_label.npy')
parser.add_argument('--lr', default=1e-5)
parser.add_argument('--scheduler-rate', default=0.1)
parser.add_argument('--scheduler-milestones', default=[6, 8])
parser.add_argument('--tcn_levels', type=int, default=1)
parser.add_argument('--tcn_kernel_size', type=int, default=3)
parser.add_argument('--graph_layers', type=int, default=2)
parser.add_argument('--graph_head', type=int, default=2)
parser.add_argument('--lambda_gmm', type=float, default=0.5)
parser.add_argument('--gmp_beta', type=float, default=5.0)
parser.add_argument('--weight_decay', type=float, default=1e-3, help='Weight decay for AdamW optimizer')